---

- name: Show running configuration
  hosts: R1
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Show running configuration
      ios_command:
        commands: show run
      register: output

    - name: Print running configuration
      debug:
        msg: " {{ output }}"
